<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQcgoyLS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQcgoyLS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQcgoyLS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQcgoyLS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQcgoyLS\App_KernelDevDebugContainer([
    'container.build_hash' => 'QcgoyLS',
    'container.build_id' => '5beaa279',
    'container.build_time' => 1776102146,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQcgoyLS');
