<?php

namespace ContainerVIsNmVt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YG5btHaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yG5btHa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yG5btHa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ListeSejoursController::donneesEntrees' => ['privates', '.service_locator.zeYAVdP.App\\Controller\\ListeSejoursController::donneesEntrees()', 'getListeSejoursControllerdonneesEntreesService', true],
            'App\\Controller\\LoginController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\LoginController::login()', 'getLoginControllerloginService', true],
            'App\\Controller\\MedecinController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\MedecinController::new()', 'getMedecinControllernewService', true],
            'App\\Controller\\SejourController::new' => ['privates', '.service_locator.zeYAVdP.App\\Controller\\SejourController::new()', 'getSejourControllernewService', true],
            'App\\Controller\\UserPatientController::register' => ['privates', '.service_locator.bpBwoAu.App\\Controller\\UserPatientController::register()', 'getUserPatientControllerregisterService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ListeSejoursController:donneesEntrees' => ['privates', '.service_locator.zeYAVdP.App\\Controller\\ListeSejoursController::donneesEntrees()', 'getListeSejoursControllerdonneesEntreesService', true],
            'App\\Controller\\LoginController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\LoginController::login()', 'getLoginControllerloginService', true],
            'App\\Controller\\MedecinController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\MedecinController::new()', 'getMedecinControllernewService', true],
            'App\\Controller\\SejourController:new' => ['privates', '.service_locator.zeYAVdP.App\\Controller\\SejourController::new()', 'getSejourControllernewService', true],
            'App\\Controller\\UserPatientController:register' => ['privates', '.service_locator.bpBwoAu.App\\Controller\\UserPatientController::register()', 'getUserPatientControllerregisterService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ListeSejoursController::donneesEntrees' => '?',
            'App\\Controller\\LoginController::login' => '?',
            'App\\Controller\\MedecinController::new' => '?',
            'App\\Controller\\SejourController::new' => '?',
            'App\\Controller\\UserPatientController::register' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ListeSejoursController:donneesEntrees' => '?',
            'App\\Controller\\LoginController:login' => '?',
            'App\\Controller\\MedecinController:new' => '?',
            'App\\Controller\\SejourController:new' => '?',
            'App\\Controller\\UserPatientController:register' => '?',
        ]);
    }
}
