<?php

namespace ContainerVIsNmVt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserPatientFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\UserPatientFormType' shared autowired service.
     *
     * @return \App\Form\UserPatientFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/UserPatientFormType.php';

        return $container->privates['App\\Form\\UserPatientFormType'] = new \App\Form\UserPatientFormType();
    }
}
