<?php

namespace ContainerQcgoyLS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMedecinFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\MedecinFormType' shared autowired service.
     *
     * @return \App\Form\MedecinFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/MedecinFormType.php';

        return $container->privates['App\\Form\\MedecinFormType'] = new \App\Form\MedecinFormType();
    }
}
