<?php

namespace ContainerQcgoyLS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSejourControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zeYAVdP.App\Controller\SejourController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zeYAVdP.App\\Controller\\SejourController::new()'] = ($container->privates['.service_locator.zeYAVdP'] ?? $container->load('get_ServiceLocator_ZeYAVdPService'))->withContext('App\\Controller\\SejourController::new()', $container);
    }
}
